
PULL: 1
STOP: 0

services:
  homepage:
    PORT: 3000
    VERSION: v1.4.5
    DESCRIPTION: My Homepage
    PUID: 1000
    PGID: 1000
    HOMEPAGE_ALLOWED_HOSTS: '*'

  immich:
    PORT: 2283
    VERSION: v1.138.1
    UPLOAD_LOCATION: ./library
    DB_DATA_LOCATION: ./postgres
    DB_PASSWORD: PgPass123456
    DB_USERNAME: postgres
    DB_DATABASE_NAME: immich

  dockge:
    PORT: 5001
    VERSION: 1.5.0

  uptime-kuma:
    PORT: 3001
    VERSION: 1.23.16

  tailscale:
    PORT: 8088
    VERSION: v1.86.2
    TS_STATE_DIR: /var/lib/tailscale
