services:
  dockge:
    image: louislam/dockge:${VERSION:-1}
    container_name: dockge
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - ${PORT:-5001}:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH}:/app/data

      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - ${SERVICES_PATH:-/opt/stacks}:${SERVICES_PATH:-/opt/stacks}
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=${SERVICES_PATH:-/opt/stacks}
    env_file:
      - .env
