services:
  uptime-kuma:
    image: louislam/uptime-kuma:${VERSION:-1}
    container_name: uptime-kuma
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ${DATA_PATH}:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${PORT:-3001}:3001
    restart: always
    env_file:
      - .env
    labels:
      - homepage.group=Services
      - homepage.name=Uptime Kuma
      - homepage.icon=uptime-kuma.png
      - homepage.href=http://truenas-scale:3001/
      - homepage.description=Uptime Kuma
networks: {}
